### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first

### ISSUE THREAD

**Issue by tndus5497** [tianweiy/CenterPoint-KITTI#5]
Hi Thank for sharing your great task.

I'm trying to training with single GPU.

If I set batch size > 1, always cuda out of memory issues are occur, so I set the batch size = 1

2021-06-03 16:12:13,039   INFO  **********************Start training home/kimsuyeon/a/CenterPoint-KITTI/tools/cfgs/kitti_models/centerpoint_rcnn(default)**********************
epochs:   0%|                                                                 | 0/80 [00:01<?, ?it/s]
Traceback (most recent call last):                                          | 0/3712 [00:00<?, ?it/s]
  File "train.py", line 198, in <module>
    main()
  File "train.py", line 153, in main
    train_model(
  File "/home/kimsuyeon/a/CenterPoint-KITTI/tools/train_utils/train_utils.py", line 86, in train_model
    accumulated_iter = train_one_epoch(
  File "/home/kimsuyeon/a/CenterPoint-KITTI/tools/train_utils/train_utils.py", line 38, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/home/kimsuyeon/a/CenterPoint-KITTI/pcdet/models/__init__.py", line 30, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/kimsuyeon/a/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kimsuyeon/a/CenterPoint-KITTI/pcdet/models/detectors/centerpoint_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/kimsuyeon/a/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kimsuyeon/a/CenterPoint-KITTI/pcdet/models/dense_heads/centerpoint_head_single.py", line 77, in forward
    targets_dict = self.assign_targets(
  File "/home/kimsuyeon/a/CenterPoint-KITTI/pcdet/models/dense_heads/centerpoint_head_single.py", line 142, in assign_targets
    heatmaps = np.array(heatmaps).transpose(1, 0).tolist()
  File "/home/kimsuyeon/a/lib/python3.8/site-packages/torch/tensor.py", line 621, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

And I got this problem. Do you have any idea?

**Comment by tianweiy** [comment]
there its a solution in that link https://github.com/open-mmlab/mmdetection3d/issues/588#issuecomment-849395413

**Comment by tndus5497** [comment]
Hi, Thank you for your help. It solved.

But still have a cuda out of memory issue (even if set the batch size to 1).

I'm using laptop and RTX3070 8gb.

Is it not enough to train this network?

**Comment by tianweiy** [comment]
It should be enough. Though I don't have 30 series gpu so I am not able to test or debug this.

**Comment by tndus5497** [comment]
Thank you for your quick response.

Do you have any idea to solve this issue? Besides adjusting the batch size.

**Comment by tianweiy** [comment]
I don't know. 

> But still have a cuda out of memory issue (even if set the batch size to 1).

This sounds too weird. Can you try other non centerpoint config and see if they work ?

**Comment by tndus5497** [comment]
Oh! Train works well when using other config besides CenterPoint(Pointpillars, Pointrcnn. etc.).

Could there be a problem with CenterPoint's config?

**Comment by tianweiy** [comment]
It could be. I will take a look at the code at the weekend

**Comment by tianweiy** [comment]
> Oh! Train works well when using other config besides CenterPoint(Pointpillars, Pointrcnn. etc.).
> 
> Could there be a problem with CenterPoint's config?

Could you try another voxelnet related config (e.g. second, pvrcnn)? it could be an issue with spconv on 30 series gpu

**Comment by tndus5497** [comment]
pvrcnn is also not working but second is working with batch size = 1

**Comment by tianweiy** [comment]
I see. It doesn't seem a bug then and it is mainly just a memory issue. CenterPoint will consume more than SECOND as we use stride 4 feature map (second uses stride 8). If you can only use batch size =1 for second then it may out of memory for centerpoint

**Comment by wanghangege** [comment]
> 

File "/home/kimsuyeon/a/lib/python3.8/site-packages/torch/tensor.py", line 621, in array
return self.numpy()

I think you can add ".cpu" in tensor.py at line 621. like this "self.cup().numpy()", I met the same error with yours, and it worked.
